---
title: "HW4-tk2886"
author: "Tanvir Khan"
output: pdf_document
---


```{r}
library(tidyverse)
```

```{r}
crash_df <- 
  read.csv("Crash.csv")
```



```{r warning = FALSE}
crash_dfn <-
  crash_df %>%
  pivot_longer(everything(), 
               names_to = "type_of_accidents",
               values_to = "Values")
```


```{r warning = FALSE}
crash_df %>% summary()

crash_df %>% summarize_if(is_numeric, sd, na.rm = T)
```

#boxplot
```{r}
boxplot(Values ~ type_of_accidents, data=crash_dfn,
        main= "Relationship between type of crash and PTSD score",
        xlab="Types of Accident",
        ylab="PTSD Score")
```


Problem 2b: 
```{r}
res1 = aov(Values ~ factor(type_of_accidents), data = crash_dfn)
summary(res1)
qf(0.99, 2, 22)
```
**Interpretation**: 


Problem 2c:
```{r}
# use pairwise.t.test() for Bonferroni, Holm, Benjamini-Hochberg
pairwise.t.test(crash_dfn$Values, crash_dfn$type_of_accidents, p.adj = 'bonferroni')

# use Tukey
Tukey_comp = TukeyHSD(res1)
Tukey_comp
plot(Tukey_comp)
```


Problem 3b:

```{r}
test_statistcs = (15-17.67)^2/17.67 + (18-17.67)^2/17.67 + (20-17.67)^2/17.67 + (18-15.33)^2/15.33 + (15-15.33)^2/15.33 + (13-15.33)^2/15.33
```

```{r}
critical_value = qchisq(.95, 1)
```


Problem 3c:

Ho: Relapse Status and types of anti-depressant are independent 


Ha: Relase Status and types of anti-depressant are associated/dependent 



